# Generated by Django 5.0.1 on 2024-01-24 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
    ]
